pipeline:
  lint_kube_yaml:
    image: fedora:25
    commands:
      - dnf install -q -y yamllint
      - "yamllint -d '{extends: default, rules: {line-length: {max: 700}}}' kube/"

  my-build:
    image: docker:17.12.0
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t developer-induction .
    when:
      event: push

  image_to_quay:
    image: docker:17.12.0
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+developer_induction" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag developer-induction quay.io/ukhomeofficedigital/developer-induction:$${DRONE_COMMIT_SHA}
      - docker tag developer-induction quay.io/ukhomeofficedigital/developer-induction:latest
      - docker push quay.io/ukhomeofficedigital/developer-induction:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/developer-induction:latest
    when:
      branch: master
      event: push

  tagged_image_to_quay:
    image: docker:17.09.0-ce
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+acp_node_hello_world" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag acp-node-hello-world:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/acp-node-hello-world:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/acp-node-hello-world:$${DRONE_TAG}
    when:
      event: tag

  deploy_to_kube:
    image: quay.io/ukhomeofficedigital/kd:v0.7.0
    secrets:
      - kube_token
    commands:
      - apk update
      - apk add curl
      - ./deploy.sh
    when:
      event: deployment
