pipeline:

  my-build:
    privileged: true
    image: docker:1.12
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t developer-induction .
    when:
      branch: master
      event: push

  image_to_quay:
    image: docker:1.12
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+developer_induction" -p=${DOCKER_PASSWORD} quay.io
      - docker tag developer-induction quay.io/ukhomeofficedigital/developer-induction:${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/developer-induction:${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd:latest
    environment:
      - KUBE_SERVER=https://kube-dev.dsp.notprod.homeoffice.gov.uk
      - KUBE_NAMESPACE=dev-induction
      - INSECURE_SKIP_TLS_VERIFY=true
    commands:
      - cd kube
      - kd -f deployment.yml -f ingress.yml -f service.yml
    when:
      event: [deployment, push]
      branch: master

services:
  dind:
    image: docker:1.12-dind
    privileged: true
    command:
      - "-s"
      - "overlay"
