---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: developer-induction-service
  name: developer-induction-service
spec:
  ports:
    - name: https
      port: 443
      targetPort: https
  selector:
    name: developer-induction
